GET http://localhost:8000/api/tokens
###

POST http://localhost:8000/api/register
Content-Type: application/json

{

"username":"joy" ,
"password":"110",
"role":"user" ,
"address":"nairobi",
"fullname":"joy wambui",
"contact_phone":"0787654675",
"email":"joy@gmail.com"

}
